package com.gamefocal.rivenworld.game.inventory.enums;

public enum InventoryDataRow {

    Empty,
    Gold_Ore,
    Silver_Ore,
    Copper_Ore,
    Coal_Ore,
    Stone,
    Iron_Ore,
    Stone_Brick,
    Copper_Ingot,
    Iron_Ingot,
    Steel_Ingot,
    Silver_Ingot,
    Gold_Ingot,
    Hide,
    Cloth,
    Leather,
    Fiber,
    Coins,
    Flint,
    Thatch,
    Wooden_Log,
    Wooden_Plank,
    Stick,
    Wool,
    Clay,
    Charcoal,
    Feather,
    Wooden_Arrow,
    Stone_Arrow,
    Iron_Arrow,
    Steel_Arrow,
    Compass,
    Fish_Net,
    Fishing_Rod,
    Stone_Hatchet,
    Iron_Hatchet,
    Steel_Hatchet,
    Stone_Pickaxe,
    Iron_Pickaxe,
    Steel_Pickaxe,
    Wooden_Bucket,
    Spade,
    Hammer,
    Waterskin,
    Torch,
    Basic_Bow,
    Crossbow,
    Wooden_Sword,
    Iron_Sword,
    Steel_Sword,
    Iron_Longsword,
    Steel_Longsword,
    Iron_Dagger,
    Steel_Dagger,
    Apple,
    Bread,
    Pear,
    Cookie,
    Flour,
    Salt,
    Raw_Meat,
    Cooked_Meat,
    Raw_Fish,
    Cooked_Fish,
    Skull,
    Book,
    Emerald,
    Ruby,
    Sapphire,
    Topaz,
    Diamond,
    Potato,
    Beet,
    Pumpkin,
    Watermelon,
    Cabbage,
    Cauliflower,
    Tomato,
    Strawberry,
    Blackberry,
    Redberry,
    Lemon,
    Lime,
    Lychee,
    Kiwi,
    Bellpepper,
    Avocado,
    Green_Beans,
    White_Grapes,
    Purple_Grapes,
    Pineapple,
    Broccoli,
    Corn,
    Banana,
    Orange,
    Peach,
    Pomegranate,
    Blueberry,
    Purpleberry,
    Yellowberry,
    Mushroom,
    Aloe_Vera,
    Poppy,
    Camomile,
    Buttercup,
    Yarrow,
    Cornflower,
    Clover_plant,
    Reeds,
    Heather,
    Leaves,
    Fertilizer,
    Feces,
    Scythe,
    Pitchfork,
    Hoe,
    Potato_Seed,
    Beet_Seed,
    Pumpkin_Seed,
    Watermelon_Seed,
    Stone_Block,
    StoneStairs_Block,
    StoneCorner_Block,
    StoneBattlement_Block,
    StoneBattlementCorner_Block,
    StoneRamp_Block,
    StoneHalf_Block,
    Clay_Block,
    Dirt_Block,
    Sand_Block,
    Thatch_Block,
    ThatchStairs_Block,
    ThatchCorner_Block,
    ThatchRamp_Block,
    ThatchHalf_Block,
    Wood_Block,
    WoodStairs_Block,
    WoodCorner_Block,
    WoodBattlement_Block,
    WoodBattlementCorner_Block,
    WoodRamp_Block,
    WoodHalf_Block,
    Iron_Block,
    Gold_Block,
    Copper_Block,
    StoneBrick_Block,
    StoneBrickStairs_Block,
    StoneBrickCorner_Block,
    StoneBrickBattlement_Block,
    StoneBrickBattlementCorner_Block,
    StoneBrickRamp_Block,
    StoneBrickHalf_Block,
    Glass_Block,
    Log_Block,
    Plaster_Block,
    DoorPlaceable,
    TablePlaceable,
    CampfirePlaceable,
    RugPlaceable,
    TorchPlaceable,
    ChestPlaceable,
    ChandelierPlaceable,
    ChairPlaceable,
    BuildingHammer,
    WindowPlaceable,
    Gate1Placeable,
    LandClaimPlaceable,
    DoorPlaceable2,
    DoorPlaceable3,
    DoorPlaceable5,
    Big_Shield,
    Small_Shield,
    FurnacePlaceable,
    bedPlaceable,
    CookingPlaceable,
    CraftingPlaceable,
    ForgePlaceable,
    TentPlaceable,
    workbenchPlaceable,
    OilLampPlaceable,
    StandOilLampPlaceable,
    WoodenClub,
    FencePlaceable1,
    FenceCornerPlaceable1,
    FencePlaceable2,
    FenceCornerPlaceable2,
    FencePlaceable3,
    FenceCornerPlaceable3,
    FencePlaceable4,
    FenceCornerPlaceable4,
    FencePlaceable5,
    FenceCornerPlaceable5,
    FencePlaceable6,
    FenceCornerPlaceable6,
    DefensiveFencePlaceable,
    SpikedFencePlaceable,
    SmallSpikedFencePlaceable,
    FenceDoorPlaceable,
    TallFencePlaceable,
    TallDefenciveSpikedFencePlaceable,
    DefenciveSpikedFencePlaceable,
    Boots3_Light_T1,
    Boots0_Light_T2,
    Boots1_Light_T3,
    Boots1_Light_T4,
    Boots1_Light_T5,
    Boots1_Light_T6,
    Boots2_Light_T7,
    Boots2_Light_T7_1,
    Boots1_Necr_Txx,
    Boots2_Heavy_T1,
    Boots2_Heavy_T2,
    Boots2_Heavy_T3,
    Boots2_Heavy_T4,
    Boots2_Heavy_T5,
    Boots2_Heavy_T6,
    Boots2_Medium_T1,
    Boots2_Medium_T2,
    Boots2_Medium_T3,
    Boots2_Medium_T4,
    Boots2_Medium_T5,
    Boots2_Medium_T6,
    Chest0_Barb_T1,
    Chest0_Barb_T5,
    Chest0_Bsmth_T1,
    Chest1_Barb_T2,
    Chest1_Barb_T3,
    Chest1_Barb_T4,
    Chest1_Bsmth_T2,
    Chest1_Crus_T5,
    Chest1_Crus_T5_Dark,
    Chest1_Crus_T5_Dark_Red,
    Chest1_Heavy_T1,
    Chest1_Heavy_T2,
    Chest1_Heavy_T3,
    Chest1_Heavy_T4,
    Chest1_Heavy_T5,
    Chest1_Heavy_T1_1,
    Chest1_Hunt_T2,
    Chest1_Hunt_T3,
    Chest1_Hunt_T4,
    Chest1_Hunt_T2_Dark,
    Chest1_Hunt_T3_Dark,
    Chest1_Light_T1,
    Chest1_Medium_T1,
    Chest1_Medium_T2,
    Chest1_Medium_T3,
    Chest1_Medium_T4,
    Chest1_Medium_T5_Green,
    Chest1_Medium_T5_Red,
    Chest1_Necr_T6,
    Helm0_Barb_T1,
    Helm0_Barb_T3,
    Helm0_Barb_T4,
    Helm0_Bsmth_T1,
    Helm0_Hunt_T2,
    Helm0_Hunt_T3,
    Helm0_Hunt_T4,
    Helm0_Light_T1,
    Helm0_Medium_T1,
    Helm0_Medium_T2,
    Helm0_Medium_T3,
    Helm0_Medium_T4,
    Helm0_MOS_T2,
    Helm0_MOS_T3,
    Helm0_MOS_T4,
    Helm0_MOS_T5,
    Helm0_MOS_T6,
    Helm0_Necr_T2,
    Helm0_Necr_T6,
    Helm1_Barb_T5,
    Helm1_Bsmth_T2,
    Helm1_Hunt_T1,
    Pants_Heavy_T1,
    Pants_Heavy_T2,
    Pants_Heavy_T4,
    Pants_Heavy_T5,
    Pants_Heavy_T6,
    Pants_Heavy_T1_Dark,
    Pants_Heavy_T2_Dark,
    Pants_Heavy_T3_Dark,
    Pants_Heavy_T4_Dark,
    Pants_Heavy_T5_Dark,
    Pants_Heavy_T6_Dark,
    Pants_Light_T1,
    Pants_Light_T2,
    Pants_Light_T3,
    Pants_Light_T4,
    Pants_Light_T5,
    Pants_Light_T1_1,
    Pants_Light_T1_Green,
    Pants_Medium_T1,
    Pants_Medium_T2,
    Pants_Medium_T3,
    Pants_Medium_T4,
    Pants_Medium_T5,
    Pants_Medium_T6,
    Pants_Medium_T1_Mod,
    Pants_Medium_T2_1,
    Pants_Medium_T2_Mod,
    Pants_Medium_T3_1,
    Pants_Medium_T4_Mod,
    Pants_Necr,
    Shirt0,
    Shirt1,
    Shirt0_Black,
    Shirt0_Green,
    Shirt0_Rich_Red,
    Shirt1_Black,
    Shirt1_Blue,
    Shirt1_Red,
    SpinningWheel,
    Anvil,
    logwatch_tower,
    logwatch_tower2,
    Fence_woodDoor,
    Fence_logDoor,
    Rock_Wall,
    Iron_Spear,
    Rope_Around_Beam_01,
    Candlelight_01,
    Candlelight_02,
    Candlelight_Stand_01,
    Candlelight_Wall_Fixation_01,
    Fabric_Carpet_01,
    Fabric_Carpet_02,
    Furniture_Bench_01,
    Furniture_Bookcase_01,
    Furniture_Chair_02,
    Furniture_Counter_01,
    Furniture_Counter_Corner_01,
    Furniture_Counter_Half_01,
    Furniture_Counter_Intersection_01,
    Furniture_Cupboard_01,
    Furniture_Shelf_01,
    Furniture_Shelf_Simple_01,
    Furniture_Small_Bench_01,
    Furniture_Stool_01,
    Furniture_Table_Round_01,
    Cart_01,
    Cattle_Fence_01,
    Cattle_Fence_02,
    Farm_Wicker_Basket_01,
    Farm_Wicker_Basket_02,
    Forge_Anvil_01,
    Forge_Bellow_01,
    Forge_Grinding_Wheel_01,
    Forge_Metal_Sign_01,
    Forge_Stump_01,
    Furniture_Bookcase_03,
    Furniture_Stool_02,
    Furniture_Table_02,
    Furniture_Table_Cloth_01,
    Furniture_Table_Cloth_02,
    Metal_Chalice_01,
    Metal_Chalice_02,
    Metal_Chalice_03,
    Metal_Chalice_04,
    Metal_Cooking_Cauldron_01,
    Metal_Cooking_Cauldron_02,
    Metal_Cooking_Cauldron_03,
    Metal_Cooking_Grill_01,
    Metal_Cooking_Pan_01,
    Metal_Cooking_Plate_01,
    Metal_Cooking_Plate_02,
    Metal_Cooking_Stand_01,
    Metal_Cooking_Tripod_02,
    Metal_Fork_01,
    Metal_Hanging_Cooking_Cauldron_02,
    Metal_Hanging_Cooking_Cauldron_03,
    Metal_Knife_01,
    Metal_Ladle_01,
    Metal_Mug_01,
    Metal_Plate_01,
    Metal_Spoon_01,
    Pottery_01,
    Pottery_02,
    Pottery_03,
    Pottery_Jar_01,
    Pottery_Pitcher_01,
    Pottery_Pitcher_02,
    Rope_Around_Beam_02,
    Tavern_Wooden_Sign_01,
    Tool_Axe_01,
    Tool_Axe_02,
    Tool_Chopper_01,
    Tool_Chopper_02,
    Tool_Farm_Flail_01,
    Tool_Farm_Scythe_01,
    Tool_Farm_Sickle_01,
    Tool_Hammer_01,
    Tool_Hammer_02,
    Tool_Hammer_03,
    Tool_Hammer_04,
    Tool_Hoe_01,
    Tool_Knife_01,
    Tool_Knife_02,
    Tool_Pitchfork_01,
    Tool_Pitchfork_02,
    Tool_Pitchfork_03,
    Tool_Rake_01,
    Tool_Rake_02,
    Tool_Saw_01,
    Tool_Saw_02,
    Tool_Shovel_02,
    Trestle_01,
    Wagon_01,
    Wagon_Front_Axle_01,
    Wheelbarrow_01,
    Wicker_Basket_01,
    Wicker_Basket_02,
    Wicker_Basket_03,
    Wicker_Basket_04,
    Wicker_Basket_05,
    Wicker_Basket_06,
    Wicker_Basket_Cover_06,
    Wooden_Armour_Stand_01,
    Wooden_Barrel_01,
    Wooden_Barrel_02,
    Wooden_Barrel_03,
    Wooden_Barrel_Cloth_01,
    Wooden_Barrel_Tavern_01,
    Wooden_Basin_01,
    Wooden_Bowl_01,
    Wooden_Bowl_02,
    Wooden_Bucket_01,
    Wooden_Chopping_Board_01,
    Wooden_Crate_01,
    Wooden_Crate_02,
    Wooden_Crate_03,
    Wooden_Crate_04,
    Wooden_Crate_Open_01,
    Wooden_Ladle_01,
    Wooden_Plate_02,
    Wooden_Plate_03,
    Wooden_Pot_01,
    Wooden_Pot_02,
    Wooden_Pot_03,
    Wooden_Rack_Tool_01,
    Wooden_Rack_Weapon_01,
    Wooden_Rack_Weapon_02,
    Wooden_Trough_01,
    Wooden_Trough_02,
    Torchholder,
    Safebox,
    StandGeneralstore,
    Battle_Axe,
    Bottlewater,
    Bowl,
    Cake,
    cart1,
    cart2,
    cart3,
    Crown,
    faucet,
    machine,
    MorningStar,
    pit,
    pitcher,
    saltwater,
    DoorPlaceable4L,
    DoorPlaceable4R,
    Toilet,
    water_r,
    tanning_rack,
    wellforwater,
    jail_1,
    jail_2,
    jail_3,






















































}
