package com.gamefocal.island.entites.orm.models.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

import com.gamefocal.island.entites.orm.OrmModel;
import com.gamefocal.island.entites.orm.models.Player;

/**
 * Class _Claims was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Claims extends OrmModel {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> CREATED_AT = PropertyFactory.createString("createdAt", String.class);
    public static final StringProperty<String> LOCATION = PropertyFactory.createString("location", String.class);
    public static final EntityProperty<Player> PLAYER = PropertyFactory.createEntity("player", Player.class);

    protected String createdAt;
    protected String location;

    protected Object player;

    public void setCreatedAt(String createdAt) {
        beforePropertyWrite("createdAt", this.createdAt, createdAt);
        this.createdAt = createdAt;
    }

    public String getCreatedAt() {
        beforePropertyRead("createdAt");
        return this.createdAt;
    }

    public void setLocation(String location) {
        beforePropertyWrite("location", this.location, location);
        this.location = location;
    }

    public String getLocation() {
        beforePropertyRead("location");
        return this.location;
    }

    public void setPlayer(Player player) {
        setToOneTarget("player", player, true);
    }

    public Player getPlayer() {
        return (Player)readProperty("player");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "createdAt":
                return this.createdAt;
            case "location":
                return this.location;
            case "player":
                return this.player;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "createdAt":
                this.createdAt = (String)val;
                break;
            case "location":
                this.location = (String)val;
                break;
            case "player":
                this.player = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.createdAt);
        out.writeObject(this.location);
        out.writeObject(this.player);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.createdAt = (String)in.readObject();
        this.location = (String)in.readObject();
        this.player = in.readObject();
    }

}
